### PR TITLE
Update 06/2020

### PR DESCRIPTION
**Pull request by 3imed-jaberi**
- update .gitignore file 🐞
- avoid generating package-lock.json ☔️
- use xo as linter 💅🏻
- update LICENSE 🗝
- use nyc over istanbul for coverage 💯
- update mocha ☕️
- update test code (use koa 2) 🧪
- update ci pipeline 🎲 (break node 1--4 | go to node ~8~ 10 -- 14)
- remove some files ❌
- improve the source code ✨
- update README.md (use koa@2 for the usage section) 📋
- better pkg.json 🎗
- add 2 examples one for koa@1.x.x and other koa@2.x.x 🤠

**READY TO 1.0.0 🚀**

### CODE REVIEW

**Comment by 3imed-jaberi** [comment]
CI failed because `mocha@8.x.x` support `Node.js@1.12.0+` ..
So, I will remove the v8 of Node.js from the pipeline.
If you want to come back with a mocha, tell me 😃

**Comment by 3imed-jaberi** [comment]
I think the module name should be changed to "@koa/save-json," and I suggest moving the [`json-body`](https://github.com/node-modules/jsonp-body) to this repo or to the organization.

**Comment by dead-horse** [comment]
can you remove yarn lockfile? others LGTM

**Comment by 3imed-jaberi** [comment]
> can you remove yarn lockfile? others LGTM

Travis on Node.js v10, v12 fails when i remove the lock file. you can see [here](https://travis-ci.org/github/koajs/locales/jobs/697075796)

**Comment by dead-horse** [comment]
why npm install will failed if there is no yarn lock?

**Comment by 3imed-jaberi** [comment]
> why npm install will failed if there is no yarn lock?

I don't know, maybe travis crush with .npmrc ... 
locally I don't have any problem.

**Comment by dead-horse** [comment]
awesome!

**Pull request merged**
